# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/workspace/project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/workspace/project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/workspace/project2/CMakeFiles /home/student/workspace/project2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/workspace/project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project2

# Build rule for target.
project2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project2
.PHONY : project2

# fast build rule for target.
project2/fast:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/build
.PHONY : project2/fast

CPU.o: CPU.cpp.o
.PHONY : CPU.o

# target to build an object file
CPU.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/CPU.cpp.o
.PHONY : CPU.cpp.o

CPU.i: CPU.cpp.i
.PHONY : CPU.i

# target to preprocess a source file
CPU.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/CPU.cpp.i
.PHONY : CPU.cpp.i

CPU.s: CPU.cpp.s
.PHONY : CPU.s

# target to generate assembly for a file
CPU.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/CPU.cpp.s
.PHONY : CPU.cpp.s

OutDevice.o: OutDevice.cpp.o
.PHONY : OutDevice.o

# target to build an object file
OutDevice.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/OutDevice.cpp.o
.PHONY : OutDevice.cpp.o

OutDevice.i: OutDevice.cpp.i
.PHONY : OutDevice.i

# target to preprocess a source file
OutDevice.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/OutDevice.cpp.i
.PHONY : OutDevice.cpp.i

OutDevice.s: OutDevice.cpp.s
.PHONY : OutDevice.s

# target to generate assembly for a file
OutDevice.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/OutDevice.cpp.s
.PHONY : OutDevice.cpp.s

Task.o: Task.cpp.o
.PHONY : Task.o

# target to build an object file
Task.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Task.cpp.o
.PHONY : Task.cpp.o

Task.i: Task.cpp.i
.PHONY : Task.i

# target to preprocess a source file
Task.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Task.cpp.i
.PHONY : Task.cpp.i

Task.s: Task.cpp.s
.PHONY : Task.s

# target to generate assembly for a file
Task.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Task.cpp.s
.PHONY : Task.cpp.s

project2.o: project2.cpp.o
.PHONY : project2.o

# target to build an object file
project2.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/project2.cpp.o
.PHONY : project2.cpp.o

project2.i: project2.cpp.i
.PHONY : project2.i

# target to preprocess a source file
project2.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/project2.cpp.i
.PHONY : project2.cpp.i

project2.s: project2.cpp.s
.PHONY : project2.s

# target to generate assembly for a file
project2.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/project2.cpp.s
.PHONY : project2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... project2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CPU.o"
	@echo "... CPU.i"
	@echo "... CPU.s"
	@echo "... OutDevice.o"
	@echo "... OutDevice.i"
	@echo "... OutDevice.s"
	@echo "... Task.o"
	@echo "... Task.i"
	@echo "... Task.s"
	@echo "... project2.o"
	@echo "... project2.i"
	@echo "... project2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

